### ISSUE TITLE
item pickup

### ISSUE THREAD

**Issue by sbradno** [sbradno/Throne#3]
Items can be dropped on the ground and a 20 second timer will call the deletion of the item.
Item pickup isn't implemented yet.

**Comment by Anthrax-** [comment]
http://pastebin.com/7AynDAjd 
i added the pickup but i didnt test it cuz i dont have any client on the pc i`m working on rightnow.

**Comment by sbradno** [comment]
Nothing is wrong with your work, it follows the project's examples just fine :+1: 
Thank you for taking care of this.
