### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Anthrax-** [sbradno/Throne#4]
when i created a char i`m able to login but after some time when i try to login i get authentication failed and then i keep getting "failed to login please try again later(11)" i tried to create another account and login and it worked
and i got another thing but its not important, when you equip an armor for example if i`m already wearing one it should replace it with the one i`m trying to equip but it doesn`t

Edit:
when it happened an error appears on auth server console with msg
Connection dropped because of an empty steam

**Comment by sbradno** [comment]
Right now I'm working on moving server configurations to files, will check into the authentication issue.. The transfer time limit is 2 seconds, that may have something to do with it if you're on a slow connection.

About equipment, I haven't made it possible to replace gear yet. You have to manually remove the equipment and replace it yourself for now. Swapping gear automatically will be implemented soon.

**Comment by Anthrax-** [comment]
i don't think it's my connection it happeneds only with special account

**Comment by sbradno** [comment]
Authentication issue should be resolved.. the authentication issue only happened for slow connections.

Will work on the equipment swapping tonight also.
