### ISSUE TITLE
Connecting to MySQL

### ISSUE THREAD

**Issue by DurbanVisuals** [sbradno/Throne#7]
Hey, I am excited to get started with this server how I cannot get it to initialize. I have changed the connection strings in both app.config's with similar:

<add name="Throne.World.Properties.Settings.DatabaseConnectionString"
             connectionString="Server=localhost;Database=db;Uid=user;Pwd=pass;"
             providerName="MySql.Data.MySqlClient" />

Can you give me a little pointer here that would be appreciated.

**Comment by sbradno** [comment]
The app.config is no longer used. the latest version has some configuration files that you can find in the folder Build/System/

**Comment by DurbanVisuals** [comment]
Oh that would make sense why I couldn't get it working. Thanks for the response and your work.
